### ISSUE TITLE
Able to change window size in LOMS with NW.js Client

### ISSUE THREAD

**Issue by TyrealGray** [SkyHarp/LegendOfMountainSea#31]
NW.js client should set window size by user's screen resolution automatically.

**Comment by CNaiko** [comment]
I will try to work on it.
Question: what is `"build-mac": "./nwjs-v0.23.5-osx-x64/nwjs.app/Contents/MacOS/nwjs .",` for in LOMS packedge.json

**Comment by TyrealGray** [comment]
@CNaiko This is a script for nwjs in mac os, same as **build-win**

**Comment by Siubaak** [comment]
it should be in order to build the native app by nwjs for macos. same as `build-win` by nwjs for win. but both of them have been ignored.

**Comment by TyrealGray** [comment]
Any update on this one? Any problem ?
