### ISSUE TITLE
Game should be running in background

### ISSUE THREAD

**Issue by TyrealGray** [SkyHarp/LegendOfMountainSea#39]
Game should be running in background, the game logic should not be blocked.

**Comment by markx** [comment]
Is this about changing the game loop to separate `update` and `render`?

**Comment by TyrealGray** [comment]
@markx more simply than that, the game is not update when it's in the background. Render works fine. The variable `delta` is already contained what we need to be done with frame between frame update. We just need to find a way that let `delta` not stop increasing in background.

**Comment by markx** [comment]
What do you mean "when it's in the background"?  Like when the tab is inactive?

**Comment by TyrealGray** [comment]
@markx yes, also within nw.js client.
