### ISSUE TITLE
Create a in-game mouse component to handle screen moving feature

### ISSUE THREAD

**Issue by TyrealGray** [SkyHarp/LegendOfMountainSea#46]
We need to create a in-game mouse component that when player moving mouse to the edge of the nw.js client, the mouse icon would change and still stay inside.

example:
When player move mouse to the left edge of screen, the mouse icon change into '>', and map will begin to moving to left.

**Comment by markx** [comment]
But moving terrain is not implemented yet, right?

**Comment by markx** [comment]
And how's this related to #57 ?

**Comment by TyrealGray** [comment]
This is not related to #57, implementation should be separated
