### ISSUE TITLE
class UIText should be able to show outline

### ISSUE THREAD

**Issue by TyrealGray** [SkyHarp/LegendOfMountainSea#50]
**Class UIText should have a feature that it could show outline when mouse move over it**

**Comment by rrandom** [comment]
I think I could help with this :). plz assign to me.

**Comment by TyrealGray** [comment]
U need to join the organization in order to take this issue, I will invite you.

**Comment by rrandom** [comment]
What color should the outline be?

**Comment by TyrealGray** [comment]
@rrandom For now, only clickable UIText should be able to show outline. If you could **filter color** according to text's color and show an **opposite color** that will also be cool. If that is too hard, then just use **white color** to show outline.
