### ISSUE TITLE
Test setup doesn't work with pixijs

### ISSUE THREAD

**Issue by markx** [SkyHarp/LegendOfMountainSea#59]
When running a test that tests source code using `PIXI`, it says `ReferenceError: PIXI is not defined`.

If you import `pixi.js` in the source code, then the test says `ReferenceError: window is not defined`. This is because pixijs depends on `window` object, and mocha environment doesn't seem to provide this global variable.

We need a better setup for the test, and some examples to show how we can test code with pixi.js

**Comment by TyrealGray** [comment]
The question is why you want to test a library which is only do rendering for you. It doesn't make sense to do that. 

Same with test document elements, if it works it will work when you run it.

**Comment by TyrealGray** [comment]
Close this issue because of discussion is done in our QQ group.
