### ISSUE TITLE
Add debug hint bar in client side

### ISSUE THREAD

**Issue by TyrealGray** [SkyHarp/LegendOfMountainSea#71]
Right now all the error is not show in the client side. We need a hint bar to show the error message to make us debugging easier.
Could start with `errorUtil.js`, add an error handling function and replace all the native `console.error`.
Add markup in `index.html` to show the error, should be easy enough at least for now.

**Comment by Siubaak** [comment]
I'm going to do this

**Comment by TyrealGray** [comment]
@Siubaak I already setup the bootstrap, just finish the logic in one place. I will merge you RP and deal with refactor. Have fun :)

**Comment by Siubaak** [comment]
@TyrealGray Hmm.... Actually I've built the views last night. But it doesn't matter for your refactor 'cause I will overwrite the native log, warn and error methods, and they can return a native HTML DOM element. you could just append the element in your views. XD

**Comment by TyrealGray** [comment]
finished in ee3c541
