### ISSUE TITLE
Animation type name should be variable not string

### ISSUE THREAD

**Issue by TyrealGray** [SkyHarp/LegendOfMountainSea#97]
Issue example: https://github.com/SkyHarp/LegendOfMountainSea/blob/master/src/render/character.js#L334

**Comment by lexcorp16** [comment]
Hi @TyrealGray I would like to take this up. To be clear, do you mean create a variable containing the string and then pass that to `this.setAnimation` ?

**Comment by TyrealGray** [comment]
@lexcorp16 Yes. And it will be better the variable also store somewhere in the static folder. Check out static folder then you will know what I mean 🙂
